// Vue/src/components/DropDownBoxComponent.vue
<script setup lang="ts">
import DxDataGrid, { type DxDataGridTypes, DxColumn, DxPaging, DxSelection, DxScrolling } from 'devextreme-vue/data-grid';
import DxDropDownBox from 'devextreme-vue/drop-down-box';
import DxSelextBox, { type DxSelectBoxTypes } from 'devextreme-vue/select-box';
import DxPopup from 'devextreme-vue/popup';
import DxButton, { type DxButtonTypes } from 'devextreme-vue/button';

import { employees, states } from '../data';
import type CustomStore from 'devextreme/data/custom_store';
import { ref } from 'vue';

const dropdownOptions = {
  width: '500px',
};
const dataGridColumns = ['FullName', 'State', 'City'];

const props = defineProps<{
  value: number,
  onValueChanged(value: number): void,
  dataSource: any[],
}>();

const currentValue = ref(props.value);
const dropDownBoxRef = ref<DxDropDownBox | null>(null);
const popupRef = ref<DxPopup | null>(null);
const dataGridRefKey = ref<DxDataGrid | null>(null);

let popupVisible = false;

const onSelectionChanged = (e: DxDataGridTypes.SelectionChangedEvent) => {
  currentValue.value = e.selectedRowKeys[0];

  props.onValueChanged(currentValue.value);

  if (e.selectedRowKeys.length > 0) {
    dropDownBoxRef.value!.instance!.close();
  }
};

const onValueChanged = (e: DxSelectBoxTypes.ValueChangedEvent): void => {
  dataGridRefKey.value?.instance?.searchByText(e.value);
};

const onClick = (e:DxButtonTypes.ClickEvent) => {
  popupRef.value?.instance?.show();
};
</script>

<template>
  <DxDropDownBox
    ref="dropDownBoxRef"
    :drop-down-options="dropdownOptions"
    :input-attr="{ 'aria-label': 'Owner' }"
    :data-source="dataSource"
    v-model:value="currentValue"
    display-expr="FullName"
    value-expr="ID"
    content-template="contentTemplate"
  >
    <template #contentTemplate="{}">
      <DxPopup
        ref="popupRef"
        :width="400"
        :height="150"
        title="Search by state:"
        :shading="false"
        :visible="false"
        container=".dx-viewport"
      >
        <div>
          <DxSelextBox
            :items="states"
            :search-enabled="true"
            :show-clear-button="true"
            @value-changed="onValueChanged"
          />
        </div>
      </DxPopup>
      <DxButton
        text="Search"
        @click="onClick"
      />
      <DxDataGrid
        ref="dataGridRefKey"
        :data-source="dataSource"
        key-expr="ID"
        :remote-operations="true"
        :height="250"
        :selected-row-keys="[currentValue]"
        :hover-state-enabled="true"
        :on-selection-changed="onSelectionChanged"
        :focused-row-enabled="true"
        :focused-row-key="currentValue"
        :columns="dataGridColumns"
      >
        <DxPaging
          :enabled="true"
          :page-size="10"
        />
        <DxScrolling mode="virtual"/>
        <DxSelection mode="single"/>
      </DxDataGrid>
    </template>
  </DxDropDownBox>
</template>

// React/src/DropDownBoxComponent.tsx
import React, { useCallback, useRef, useState } from 'react';

import {
  Button,
  DataGrid, DropDownBox, Popup, SelectBox,
} from 'devextreme-react';
// import { ColumnEditCellTemplateData } from 'devextreme/ui/data_grid';
import { type DataGridTypes, type DataGridRef, Selection } from 'devextreme-react/data-grid';
import { type SelectBoxTypes } from 'devextreme-react/select-box';
import { type DropDownBoxRef } from 'devextreme-react/drop-down-box';
// import { ValueChangedEvent } from 'devextreme/ui/select_box';
import { employees, states } from './data';

const dropdownOptions = {
  width: '500px',
};
const dataGridColumns = ['FullName', 'State', 'City'];

function DropDownBoxComponent(props: DataGridTypes.ColumnEditCellTemplateData): JSX.Element {
  const dropDownBoxRef = useRef<DropDownBoxRef>(null);
  const [popupVisible, setPopupVisible] = useState(false);
  const [selectedRowKeys, setSelectedRowKeys] = useState([props.data.value]);
  const dataGridRef = useRef<DataGridRef>(null);

  const contentRender = useCallback(() => {
    const onSelectionChanged = useCallback((args: DataGridTypes.SelectionChangedEvent): void => {
      setSelectedRowKeys(args.selectedRowKeys);
      dropDownBoxRef.current?.instance().close();
      setPopupVisible(false);
      props.data.setValue(args.selectedRowKeys[0]);
    }, []);

    const onValueChanged = useCallback((e: SelectBoxTypes.ValueChangedEvent): void => {
      dataGridRef.current?.instance().searchByText(e.value);
    }, []);

    const onClick = useCallback((): void => {
      setPopupVisible(true);
    }, []);

    return (
      <React.Fragment>
        <Popup
          width={400}
          height={150}
          title="Search by state:"
          shading={false}
          visible={popupVisible}>
          <SelectBox
            items={states}
            searchEnabled={true}
            showClearButton={true}
            onValueChanged={onValueChanged}></SelectBox>
        </Popup>
        <Button
          text="Search"
          onClick={onClick}></Button>
        <DataGrid
          ref={dataGridRef}
          columns={dataGridColumns}
          keyExpr="ID"
          dataSource={employees}
          height={250}
          defaultFocusedRowKey={selectedRowKeys[0]}
          selectedRowKeys={selectedRowKeys}
          focusedRowEnabled={true}
          onSelectionChanged={onSelectionChanged}>
          <Selection mode="single"></Selection>
        </DataGrid>
      </React.Fragment>
    );
  }, [popupVisible]);

  return (
    <React.Fragment>
      <DropDownBox
        ref={dropDownBoxRef}
        value={selectedRowKeys}
        defaultOpened={true}
        dropDownOptions={dropdownOptions}
        dataSource={employees}
        valueExpr="ID"
        displayExpr="FullName"
        contentRender={contentRender}
      />
    </React.Fragment>
  );
}

export default DropDownBoxComponent;
